//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContosoSite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DanilichDBEntities11 : DbContext
    {
        public DanilichDBEntities11()
            : base("name=DanilichDBEntities11")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<авто> авто { get; set; }
        public virtual DbSet<заказы> заказы { get; set; }
        public virtual DbSet<запчасти> запчасти { get; set; }
        public virtual DbSet<поставщики> поставщики { get; set; }
        public virtual DbSet<сотрудники> сотрудники { get; set; }
        public virtual DbSet<авторизация> авторизация { get; set; }
    }
}
