//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContosoSite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class авто
    {
        public int код { get; set; }
        public int код_автомобиля { get; set; }
        public string vin { get; set; }
        public string марка_автомобиля { get; set; }
        public string модель_автомобиля { get; set; }
        [DisplayFormat(DataFormatString= "{0:dd/MM/yyyy}")]
        public DateTime год_выпуска { get; set; }
    
        public virtual заказы заказы { get; set; }
    }
}
