//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContosoSite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class заказы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public заказы()
        {
            this.авто = new HashSet<авто>();
        }
    
        public int код_заказа { get; set; }
        public int код_автомобиля { get; set; }
        public Nullable<int> код_клиента { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime дата_приема { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime дата_выдачи { get; set; }
        public string вид_работ { get; set; }
        public Nullable<decimal> сумма_работ { get; set; }
        public int товары_для_ремонта { get; set; }
        public int сотрудник { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<авто> авто { get; set; }
        public virtual запчасти запчасти { get; set; }
        public virtual сотрудники сотрудники { get; set; }
    }
}
